# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3bfaa87b4b7cdbf5734fb9ab377f71e0"
application_url = "https://fm-ist-remedies-lid.trycloudflare.com"
embedded = true
name = "Automation X"
handle = "automation-x"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products"

[auth]
redirect_urls = [
  "https://fm-ist-remedies-lid.trycloudflare.com/auth/callback",
  "https://fm-ist-remedies-lid.trycloudflare.com/auth/shopify/callback",
  "https://fm-ist-remedies-lid.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "essentialhubstore.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
